### ISSUE TITLE
[BUG] Plugin unsable due to DOMPurify

### ISSUE THREAD

**Issue by piotryordanov** [ogame-infinity/web-extension#196]
![image](https://github.com/ogame-infinity/web-extension/assets/48773775/67661812-1242-49ae-9020-7e0bce0cd3eb)
I keep on getting this error. Forces me to reload the page all the time. Ogame becomes totally unusable otherwise!

Any idea how to fix it? I can look in the code!

**Comment by Bishop341-B** [comment]
Yeah... this a known nasty bug that was introduced some versions ago. It happens sometimes (or always) to some people, but not to all, and we don't know yet why exactly only for these people. The bug seems to be because some race condition in the code (loading/calling the lib i suspect), but we don't know what/when exactly trigger it.

We are in process to fix it getting rid of DOMpurify component, because this will bring also a little speed bump and get rid of playing with innerHTML. But this process is slow, there are tons of code to replace to do that. Great progress has been done so far (see #170 and #183), but still there some DOMpurify uses left to replace.

Sorry but until the complete elimination of the DOMpurify component or maybe if someone find the bug trigger, this bug can not be fixed. You may try to use another browser or try to use a new browser profile as a workaround, as this **it worked for some of the affected people, but no guarantee on this**.

**Comment by IbaiArricibita** [comment]
I realized a little thing with this DOMPurify problema, and (to me at least) it only happens if i navigate using left menu. It wont happen if navigating via the url bar or F5...

**Comment by Bishop341-B** [comment]
I tried to make a workaround. Can you test if this fix (to some extent or fully) the problem?

[https://github.com/Bishop341-B/ogame-infinity/tree/b40ca57269f28180952f7587c0c8b3a92c959804](url)

Download the code here, disable regular ogi extension and then load the test extension as a developer extension.

![imagen](https://github.com/ogame-infinity/web-extension/assets/13818551/0b8482c0-dfaa-478d-9262-ec2b5c6c2f6a)

**Comment by IbaiArricibita** [comment]
The little I tested it seems to work, not showing the "DOMPurify is not defined" problem anymore.

**Comment by Bishop341-B** [comment]
> The little I tested it seems to work. Not showing the "DOMPurify is not defined" problem anymore.

Great :+1: 

Did you have the problem on a PC browser or in a mobile browser?

**Comment by IbaiArricibita** [comment]
PC Browser
